train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      repeat: 1
      cache: in_memory
      last_k: 120000
      skip_every: 30
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size_min: 32
      inp_size_max: 64
      scale_min: 2
      scale_max: 4
      augment: true
      sample_q: 4096
      vary_q: true
      max_q: 8192
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      first_k: 42000
      skip_every: 168
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size_min: 32
      inp_size_max: 32
      scale_min: 2
      scale_max: 6
      sample_q: 4096
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: liif_inr
  args:
    encoder_spec:
      name: rdn
      args:
        D: 18
        C: 4
        G: 32
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
        has_bn: true
        act: "gelu"

optimizer:
  name: adamw
  args:
    lr: 1.e-4

epoch_max: 100
multi_step_lr:
  milestones: [10, 20, 30, 40]
  gamma: 0.5

epoch_val: 1
epoch_save: 1
