train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      repeat: 5
      cache: in_memory
      last_k: 120000
      skip_every: 30
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      scale_min: 1
      sample_q: 2304
  batch_size: 1
  num_workers: 4
  pin_memory: true

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      first_k: 42000
      skip_every: 168
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      scale_min: 1
      sample_q: 2304
  batch_size: 1
  num_workers: 4
  pin_memory: true

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: ITNSR
  args:
    feat_unfold: True
    local_ensemble: True
    scale_token: True
    encoder_spec:
      name: rdn
      args:
        D: 10
        C: 2
        G: 32
        no_upsampling: true

    imnet_spec:
      name: mlp
      args:
        in_dim: 2304
        hidden_list: [256,256,256,256]
        act: 'gelu'

optimizer:
  name: adamw
  args:
    lr: 2.e-4
epoch_max: 100
multi_step_lr:
  milestones: [10, 20, 40, 60, 80]
  gamma: 0.5

epoch_val: 1
epoch_save: 1

resume: ~
pre_train: ~