train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      repeat: 2
      cache: in_memory
      last_k: 400
      skip_every: 1
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size_min: 32
      inp_size_max: 64
      scale_min: 2
      scale_max: 4
      augment: true
      color_augment: true
      color_augment_strength: 0.05
      sample_q: 4096
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      first_k: 150
      skip_every: 3
      repeat: 2
      cache: in_memory
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size_min: 48
      inp_size_max: 48
      scale_min: 2
      scale_max: 6
      sample_q: 4096
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: ITNSR
  args:
    feat_unfold: True
    local_ensemble: True
    scale_token: True
    encoder_spec:
      name: resnexter
      args:
        num_colors: 3
        layers: [3,2,1]
        num_filters: 64
        out_filters: 128
        zero_init_residual: false
    imnet_spec:
      name: mlp
      args:
        in_dim: 4
        hidden_list: [256,256,256,256]
        act: mish
        use_sn: false
        has_norm: true
    embedding_scale:
      name: mlp
      args:
        in_dim: 2
        out_dim: 2
        hidden_list: [64,64]
        act: leaky_relu
    embedding_coord:
      name: mlp
      args:
        in_dim: 2
        out_dim: 2
        hidden_list: [256,256]
        act: leaky_relu

d_model:
  name: freq_disc
  args:
    model_spec:
      name: mlp
      args:
        in_dim: 27648
        out_dim: 1
        use_sn: false
        hidden_list: [256, 256, 256, 256]
        act: gelu
start_disc: 2

losses:
  q:
    dst:
      fn:
        name: dists
        args:
      weight: 1.0
    bce:
      fn:
        name: bce_with_logits
        args:
      weight: 0.2
  img:
    freq:
      fn:
        name: fourier_space
        args:    
      weight: 0.025
    msL1:
      fn:
        name: multiscale_l1
        args:
          scale: 3
      weight: 1.0
  teacher:
    kl:
      fn: 
        name: teacher_kl
        args: 
          T: 0.1
      weight: 0.1
      
optimizer:
  name: adamw
  args:
    lr: 2.e-4
epoch_max: 100
multi_step_lr:
  milestones: [90]
  gamma: 0.5

epoch_val: 1
epoch_save: 1

resume: ~
pre_train: ~