train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      repeat: 25
      cache: in_memory
      first_k: 3400
      skip_every: 3
  wrapper:
    name: sr-explicit-downsampled-randcrop
    args:
      inp_size: 32
      scale_min: 4
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      last_k: 131
      repeat: 100
      cache: in_memory
  wrapper:
    name: sr-explicit-downsampled-randcrop
    args:
      inp_size: 32
      scale_min: 4
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: ddbpn
      args:
        no_upsampling: False
        use_pa: True
        n_feats_in: 128
        n_feats: 32
        n_feats_out: 256
        depth: 5
        scale: 4
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100
multi_step_lr:
  milestones: [20, 40, 60, 80]
  gamma: 0.5

epoch_val: 1
epoch_save: 10
