train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/frames/
      repeat: 3
      cache: in_memory
      first_k: 600
      skip_every: 1
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size: 32
      inp_size_min: 32
      inp_size_max: 64
      scale_min: 2
      scale_max: 6
      augment: true
      sample_q: 4096
      color_augment: false
      color_augment_strength: 0.2
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /content/full/
      last_k: 140
      repeat: 1
      skip_every: 3
      cache: in_memory
  wrapper:
    name: sr-setrange-downsampled-randcrop
    args:
      inp_size: 32
      inp_size_min: 32
      inp_size_max: 128
      scale_min: 2
      scale_max: 6
      sample_q: 4096
      return_hr: true
  batch_size: 1
  num_workers: 4
  pin_memory: true
batch_eval: 1000

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr
      args:
        n_resblocks: 32
        n_feats: 64
        act: gelu
        use_bn: false
        use_pa: true
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
        act: sine_learnable
        has_norm: true
        norm: nn.LayerNorm
        has_bias: false
        use_residual: true
        use_sn: false


optimizer:
  name: adamw
  args:
    lr: 1.e-4
epoch_max: 500
multi_step_lr:
  milestones: [100, 200, 300, 400]
  gamma: 0.5

epoch_val: 1
epoch_save: 10

losses:
  q:
    l1:
      fn:
        name: l1
        args:
      weight: 1.0
    fspace:
      fn:
        name: fourier_space
        args:
      weight: 1.0
    sobol:
      fn:
        name: sobolev_norm
        args:
      weight: 0.1